### 추천 테스트
POST http://localhost:8000/api/ai/recommend/crawling/by-user
Content-Type: application/json

{
  "user_id": "test-user-2"
}

### 자기소개 생성 테스트
POST http://localhost:8000/api/ai/intro
Content-Type: application/json

{
  "user_id": "test-user-2"
}

### 관심사 추출 테스트
POST http://localhost:8000/api/ai/interest/user
Content-Type: application/json

{
  "user_id": "test-user-2"
}

### 관심사 추출 테스트
POST http://localhost:8000/api/ai/interest/room
Content-Type: application/json

{
  "room_id": "2"
}

###
POST http://localhost:8000/api/wevity/test

###
GET http://3.107.196.48:8000/api/wevity/1