// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2b5rRd5D3_5NeLycg37fs91UoOSdGVp0',
    appId: '1:254852353422:android:e67224c358d83709a128df',
    messagingSenderId: '254852353422',
    projectId: 'semothon-97e9d',
    storageBucket: 'semothon-97e9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxhGZPZVcccaL_wMkONiQm1-wkYEYy51s',
    appId: '1:254852353422:ios:ee21d6f827a13f76a128df',
    messagingSenderId: '254852353422',
    projectId: 'semothon-97e9d',
    storageBucket: 'semothon-97e9d.firebasestorage.app',
    androidClientId: '254852353422-7cj544e4p9egi6vnopuc3dqj152j5gp3.apps.googleusercontent.com',
    iosClientId: '254852353422-r19gem9dko9sudi5vgfjhpa832595fl1.apps.googleusercontent.com',
    iosBundleId: 'com.unus',
  );
}
