import 'dart:math';

import 'package:flutter_app/dto/user_dto.dart';

List<UserDTO> dummyUsers = [
  UserDTO(
    userId: 'a3f1c9x7',
    nickname: '날아다니는 전자맨',
    department: '전자정보학과',
    studentId: '20',
    birthdate: DateTime(2001, 6, 15),
    gender: 'MALE',
    profileImageUrl: 'https://randomuser.me/api/portraits/men/75.jpg',
    introText: '회로보다 사람을 더 좋아합니다. 다양한 프로젝트 경험 있어요.',
    shortIntro: '전자회로 고수입니다!',
    socialProvider: '',
    socialId: '',
    createdAt: DateTime(2023, 5, 30),
  ),
  UserDTO(
    userId: 'b8z9lm4q',
    nickname: '끄적이는 코딩요정',
    department: '소프트웨어학과',
    studentId: '21',
    birthdate: DateTime(2002, 2, 3),
    gender: 'FEMALE',
    profileImageUrl: 'https://randomuser.me/api/portraits/women/68.jpg',
    introText: '백엔드보다 프론트가 좋아요. React/Flutter 다룹니다.',
    shortIntro: 'UI는 내 손 안에',
    socialProvider: '',
    socialId: '',
    createdAt: DateTime(2023, 6, 12),
  ),
  UserDTO(
    userId: 'd4k7pw9n',
    nickname: '디자인 정복자',
    department: '시각디자인학과',
    studentId: '19',
    birthdate: DateTime(2000, 9, 27),
    gender: 'MALE',
    profileImageUrl: 'https://randomuser.me/api/portraits/men/23.jpg',
    introText: '포트폴리오 피드백 가능합니다. UI/UX 공모전 다수 수상',
    shortIntro: '디자인 멘토',
    socialProvider: '',
    socialId: '',
    createdAt: DateTime(2023, 3, 10),
  ),
  UserDTO(
    userId: 'm1n0uv2t',
    nickname: '백엔드 몬스터',
    department: '컴퓨터공학과',
    studentId: '18',
    birthdate: DateTime(1999, 12, 5),
    gender: 'MALE',
    profileImageUrl: 'https://randomuser.me/api/portraits/men/41.jpg',
    introText: 'Java, Spring Boot, REST API 설계 전공자입니다.',
    shortIntro: 'API 마스터',
    socialProvider: '',
    socialId: '',
    createdAt: DateTime(2022, 12, 15),
  ),
  UserDTO(
    userId: 'r6s3yb0a',
    nickname: 'UX 탐험가',
    department: '인간중심디자인학과',
    studentId: '22',
    birthdate: DateTime(2003, 3, 20),
    gender: 'FEMALE',
    profileImageUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
    introText: '사용자 중심 사고를 바탕으로 멘토링합니다.',
    shortIntro: 'UX 감성 터진다',
    socialProvider: '',
    socialId: '',
    createdAt: DateTime(2023, 4, 1),
  ),
  UserDTO(
    userId: 'm2l4kj8x',
    nickname: '백엔드 마스터',
    department: '컴퓨터공학과',
    studentId: '20',
    birthdate: DateTime(2001, 5, 12),
    gender: 'MALE',
    profileImageUrl: 'https://randomuser.me/api/portraits/men/45.jpg',
    introText: 'Java와 Spring Boot로 대규모 서버를 개발했습니다.',
    shortIntro: 'REST API 장인',
    socialProvider: '',
    socialId: '',
    createdAt: DateTime(2023, 5, 10),
  ),
  UserDTO(
    userId: 'f7s3pb9r',
    nickname: '기획의 신',
    department: '산업디자인학과',
    studentId: '21',
    birthdate: DateTime(2002, 9, 8),
    gender: 'FEMALE',
    profileImageUrl: 'https://randomuser.me/api/portraits/women/54.jpg',
    introText: '사용자 경험을 고려한 서비스 기획이 강점입니다.',
    shortIntro: 'UX 전략가',
    socialProvider: '',
    socialId: '',
    createdAt: DateTime(2023, 6, 2),
  ),
  UserDTO(
    userId: 'x1n9qv2d',
    nickname: '프론트 공장장',
    department: '소프트웨어학과',
    studentId: '19',
    birthdate: DateTime(2000, 2, 19),
    gender: 'MALE',
    profileImageUrl: 'https://randomuser.me/api/portraits/men/12.jpg',
    introText: 'React와 Flutter 둘 다 다룹니다.',
    shortIntro: 'UI 개발은 내 손안에',
    socialProvider: '',
    socialId: '',
    createdAt: DateTime(2023, 3, 20),
  ),
  UserDTO(
    userId: 'k3a2yt0m',
    nickname: '디자인 마녀',
    department: '시각디자인학과',
    studentId: '22',
    birthdate: DateTime(2003, 1, 7),
    gender: 'FEMALE',
    profileImageUrl: 'https://randomuser.me/api/portraits/women/32.jpg',
    introText: '비주얼 디자이너를 꿈꾸며 Figma에 진심입니다.',
    shortIntro: 'Figma 덕후',
    socialProvider: '',
    socialId: '',
    createdAt: DateTime(2023, 4, 5),
  ),
  UserDTO(
    userId: 'z4r7ox9e',
    nickname: '데이터 분석러',
    department: '데이터사이언스학과',
    studentId: '20',
    birthdate: DateTime(2001, 11, 22),
    gender: 'MALE',
    profileImageUrl: 'https://randomuser.me/api/portraits/men/60.jpg',
    introText: '파이썬과 pandas로 데이터를 요리합니다.',
    shortIntro: '분석 좋아하는 공대생',
    socialProvider: '',
    socialId: '',
    createdAt: DateTime(2023, 2, 10),
  ),
  UserDTO(
    userId: 'w5u8vc7k',
    nickname: '기술창업러',
    department: '경영학과',
    studentId: '18',
    birthdate: DateTime(1999, 7, 14),
    gender: 'MALE',
    profileImageUrl: 'https://randomuser.me/api/portraits/men/27.jpg',
    introText: '창업과 서비스 런칭 경험이 있습니다.',
    shortIntro: '스타트업 실무자',
    socialProvider: '',
    socialId: '',
    createdAt: DateTime(2022, 12, 1),
  ),
  UserDTO(
    userId: 'c6b1tp9z',
    nickname: '심리학 개발자',
    department: '심리학과',
    studentId: '23',
    birthdate: DateTime(2004, 4, 3),
    gender: 'FEMALE',
    profileImageUrl: 'https://randomuser.me/api/portraits/women/21.jpg',
    introText: '심리학을 기반으로 한 UX 연구를 진행하고 있어요.',
    shortIntro: 'UX 심리 파헤치기',
    socialProvider: '',
    socialId: '',
    createdAt: DateTime(2023, 6, 1),
  ),
  UserDTO(
    userId: 'b7x6mf0l',
    nickname: 'AI 모델러',
    department: 'AI학과',
    studentId: '21',
    birthdate: DateTime(2002, 8, 25),
    gender: 'FEMALE',
    profileImageUrl: 'https://randomuser.me/api/portraits/women/48.jpg',
    introText: 'PyTorch로 딥러닝 모델을 학습시키고 있습니다.',
    shortIntro: '머신러닝 장인',
    socialProvider: '',
    socialId: '',
    createdAt: DateTime(2023, 3, 5),
  ),
  UserDTO(
    userId: 'h9p2lw6q',
    nickname: '모션 마스터',
    department: '디지털미디어학과',
    studentId: '20',
    birthdate: DateTime(2001, 10, 10),
    gender: 'MALE',
    profileImageUrl: 'https://randomuser.me/api/portraits/men/76.jpg',
    introText: '에프터이펙트와 프리미어 프로 다룹니다.',
    shortIntro: '움직이는 건 나한테 맡겨!',
    socialProvider: '',
    socialId: '',
    createdAt: DateTime(2023, 1, 15),
  ),
  UserDTO(
    userId: 'q8n4gz3v',
    nickname: '서비스 디자이너',
    department: '서비스디자인학과',
    studentId: '19',
    birthdate: DateTime(2000, 6, 28),
    gender: 'FEMALE',
    profileImageUrl: 'https://randomuser.me/api/portraits/women/35.jpg',
    introText: '사용자 여정을 기반으로 서비스를 설계합니다.',
    shortIntro: '서비스 기획 전문가',
    socialProvider: '',
    socialId: '',
    createdAt: DateTime(2023, 5, 3),
  ),
];

List<UserDTO> randomUsers(int n) {
  final random = Random();
  final List<UserDTO> copy = List<UserDTO>.from(dummyUsers);
  copy.shuffle(random);
  return copy.sublist(0, n);
}
