spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # 기본값 dev

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        timezone:
          default_storage: NORMALIZE
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 300

external:
  fastapi:
    url: ${FASTAPI_BASE_URL}

logging:
  level:
    root: INFO
    com.zaxxer.hikari: DEBUG
    org.hibernate.engine.jdbc.connections: DEBUG

cloud: #S3 설정
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    s3:
      bucket: ${AWS_BUCKET_NAME}